from flask_wtf import FlaskForm
from wtforms import (StringField, TextAreaField, IntegerField, BooleanField,
           RadioField, FloatField)
from wtforms.validators import InputRequired, Length


class ProductForm(FlaskForm):
  id = IntegerField('Id')
  name = StringField('Name')
  price = FloatField('Price')
  description = TextAreaField('Description')
  images = StringField('Images')
  weight = FloatField('Weight(kg)')
  length = FloatField('Length(cm)')
  width = FloatField('Width(cm)')
  height = FloatField('Height(cm)')
  attribute_1_name = StringField('Attribute 1 name')
  attribute_1_value = StringField('Attribute 1 value(s)')
  attribute_1_visible = StringField('Attribute 1 visible')
  attribute_1_global = StringField('Attribute 1 global')
  attribute_1_default = StringField('Attribute 1 default')
  attribute_2_name = StringField('Attribute 2 name')
  attribute_2_value = StringField('Attribute 2 value(s)')
  attribute_2_visible = StringField('Attribute 2 visible')
  attribute_2_global = StringField('Attribute 2 global')
  attribute_2_default = StringField('Attribute 2 default')
  attribute_3_name = StringField('Attribute 3 name')
  attribute_3_value = StringField('Attribute 3 value(s)')
  attribute_3_visible = StringField('Attribute 3 visible')
  attribute_3_global = StringField('Attribute 3 global')
  attribute_3_default = StringField('Attribute 3 default')
  attribute_4_name = StringField('Attribute 4 name')
  attribute_4_value = StringField('Attribute 4 value(s)')
  attribute_4_visible = StringField('Attribute 4 visible')
  attribute_4_global = StringField('Attribute 4 global')
  attribute_4_default = StringField('Attribute 4 default')
  attribute_5_name = StringField('Attribute 5 name')
  attribute_5_value = StringField('Attribute 5 value(s)')
  attribute_5_visible = StringField('Attribute 5 visible')
  attribute_5_global = StringField('Attribute 5 global')
  attribute_5_default = StringField('Attribute 5 default')
  attribute_6_name = StringField('Attribute 6 name')
  attribute_6_value = StringField('Attribute 6 value(s)')
  attribute_6_visible = StringField('Attribute 6 visible')
  attribute_6_global = StringField('Attribute 6 global')
  attribute_6_default = StringField('Attribute 6 default')
  attribute_7_name = StringField('Attribute 7 name')
  attribute_7_value = StringField('Attribute 7 value(s)')
  attribute_7_visible = StringField('Attribute 7 visible')
  attribute_7_global = StringField('Attribute 7 global')
  attribute_7_default = StringField('Attribute 7 default')
  attribute_8_name = StringField('Attribute 8 name')
  attribute_8_value = StringField('Attribute 8 value(s)')
  attribute_8_visible = StringField('Attribute 8 visible')
  attribute_8_global = StringField('Attribute 8 global')
  attribute_8_default = StringField('Attribute 8 default')